### ISSUE TITLE
panel heatmap y not sorted

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic-grafana-datasource#49]
in grafana 6 i use heatmap panel with this query:

average by f
from points
where
$key = "orfees"
and st = "i"
and host = "rsdb"

everithing seems good except for Y: the y axes is not sorted by f (average by f)

![image](https://user-images.githubusercontent.com/20299472/55232210-13257400-5225-11e9-90b8-4ccbc5c8b8d6.png)

**Comment by lucilecoutouly** [comment]
hello,
could you help me to sort series ?

**Comment by lucilecoutouly** [comment]
@dflemstr :could you help me

**Comment by dmichel1** [comment]
hi @lucilecoutouly I believe you are still using https://github.com/udoprog/udoprog-heroic-datasource and not this plugin, as this plugin doesn't support the heroic query language yet.

Could you try installing this plugin and see if the heatmap is still broken?

https://github.com/spotify/heroic-grafana-datasource#how-to-install

**Comment by lucilecoutouly** [comment]
thank you for the reply.
in fact i try both of them 
![image](https://user-images.githubusercontent.com/20299472/56812628-9ee9ea80-683b-11e9-91ec-5789a79f9b33.png)

**Comment by dmichel1** [comment]
👍 cool thanks for confirming - it does indeed look like a bug - i'll make sure to bring this up in our next planning session to address. 

i take it heroic is not returning series sorted by the bound in ascending order, as mentioned here https://grafana.com/docs/features/panels/heatmap/#pre-bucketed-data not sure what the solution is here yet.

**Comment by lucilecoutouly** [comment]
yes it is the pre-bucketed-data that i use to show heatmap.
thanks for your help

**Comment by jsferrei** [comment]
Shot in the dark here, but what happens if you change "Format As" to table?

**Comment by lucilecoutouly** [comment]
it doesn't send anything
![image](https://user-images.githubusercontent.com/20299472/56814071-9e9f1e80-683e-11e9-843d-69a0b43c07fe.png)

**Comment by hexedpackets** [comment]
@lucilecoutouly I'm having trouble reproducing this, the queries I've tried (with Grafana v6.0.1) created a correctly ordered heatmap.

Can you copy the query from the Query Inspector and share it? You'll probably need to post it to pastebin or as a gist or something since it will be a large amount of text.

**Comment by lucilecoutouly** [comment]
@hexedpackets
grafana 6.1.6

**Comment by hexedpackets** [comment]
This is an issue with how Grafana sorts strings. When Grafana is given non-numerical values for the y-axis on heatmaps it will do an alphabetic sort. One way to make that sort behave in a more obvious way is by aliasing the time series. 

For example, I setup a graph that has HTTP status codes in a tag. Aliasing it similarly to your graph with `status-code=[[tag_status-code]]` gives this:
![2019-05-10_100028_143388497](https://user-images.githubusercontent.com/3689782/57540796-8e497200-731b-11e9-9aab-100c57f7c132.png)

Changing the alias to have just the tag without a prefix, `[[tag_status-code]]`, results in:
![2019-05-10_100028_143388497](https://user-images.githubusercontent.com/3689782/57540773-796cde80-731b-11e9-9fd2-761244f88925.png)

All tags in Heroic are strings, so this is still sorting alphabetically and won't always give the expected result, but its as close as we can get.

**Comment by lucilecoutouly** [comment]
ok but how you change the alias ?
i have:
"f=488795"
where is in grafana alias  ?
thanks

**Comment by hexedpackets** [comment]
Its the field labelled "Alias By" in the query editor. The double-square brackets are a template for using fields from the query result - eg `[[tag_status-code]]` in my example gets replaced by the value of the Heroic tag `status-code`.

**Comment by lucilecoutouly** [comment]
@hexedpackets
thank you it works.
