### ISSUE TITLE
Building a complex filter errors out

### ISSUE THREAD

**Issue by dmichel1** [spotify/heroic-grafana-datasource#52]
When building a complex filter often it errors out and can cause the filter not to be added correctly.

![Screen Shot 2019-06-25 at 5 15 44 PM](https://user-images.githubusercontent.com/677960/60134164-e3770100-976c-11e9-939b-7b10e24a106c.png)

**Comment by lmuhlha** [comment]
Happens when you add a complex filter to a panel, save, come back to it and click on the complex filter. Error pops up if you look for it but it doesn't actually break functionality.
